# Generated by Django 4.1.7 on 2023-08-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                (
                    "slotid",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("available", models.CharField(max_length=45)),
                ("ptime", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "parking_slot", "managed": False,},
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("resnum", models.IntegerField(primary_key=True, serialize=False)),
                ("plotid", models.IntegerField()),
                ("carnum", models.CharField(max_length=45)),
                ("intime", models.DateTimeField(blank=True, null=True)),
                ("outtime", models.DateTimeField(blank=True, null=True)),
                ("usagetime", models.IntegerField(blank=True, null=True)),
                ("finished", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "reservation", "managed": False,},
        ),
        migrations.CreateModel(
            name="TutorialPost",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
            ],
            options={"db_table": "tutorial_post", "managed": False,},
        ),
        migrations.DeleteModel(name="Post",),
    ]
